server:
  host: 0.0.0.0
  port: 8080
database:
  host: 43.136.170.73
  dbname: street-stall
  port: 3306
  username: street-stall
  password: D82bFLHijrpmtxLx
email:
  host: smtp.163.com
  username: youlingdada@163.com
  password: MDQVWHDMEHVTOHYS
  port: 25
redis:
  host: localhost
  port: 6379
  username:
  password:
  db: 1