definitions:
  query.BoothAddQuery:
    description: 摊位增加请求模型
    properties:
      address:
        description: 摊位地址
        type: string
      latitude:
        description: 维度
        type: number
      longitude:
        description: 经度
        type: number
      name:
        description: 摊位名称
        type: string
      status:
        description: 摊位状态
        type: integer
      type:
        description: 摊位类型
        type: integer
      userId:
        description: 用户id
        type: integer
    type: object
  query.BoothTypeAddQuery:
    properties:
      description:
        description: 描述
        type: string
      iconId:
        description: 图标文件id
        type: integer
      name:
        description: 名称
        type: string
    type: object
  query.BoothTypeEditQuery:
    properties:
      description:
        description: 描述
        type: string
      iconId:
        description: 图标文件id
        type: integer
      name:
        description: 名称
        type: string
    type: object
  query.EditBoothQuery:
    description: 编辑摊位请求模型
    properties:
      address:
        description: 摊位地址
        type: string
      bId:
        description: 摊位id
        type: integer
      latitude:
        description: 维度
        type: number
      longitude:
        description: 经度
        type: number
      name:
        description: 摊位名称
        type: string
      type:
        description: 摊位类型
        type: integer
    type: object
  query.UserAddQuery:
    description: 用户注册数据
    properties:
      code:
        description: 邮箱验证码
        type: string
      email:
        description: 用户邮箱
        type: string
      password:
        description: 用户密码
        type: string
      phone:
        description: 用户电话
        type: string
      userType:
        description: 用户类型 0 商户（卖家） 1 用户（买家）默认0
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  query.UserLoginQuery:
    description: 用户登录数据
    properties:
      loginType:
        description: 登录方式 0 用户名(默认) 1 邮箱 2 电话
        type: integer
      password:
        description: 用户密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  query.UserUpdateInfoQuery:
    description: 用户信息更新模型
    properties:
      avatarId:
        description: 用户头像链接
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  query.UserUpdatePwdQuery:
    description: 用户修改密码模型
    properties:
      code:
        description: 邮箱验证码
        type: string
      email:
        description: 邮箱
        type: string
      password:
        description: 用户密码
        type: string
    type: object
  query.WaresAddQuery:
    description: 添加商品模型
    properties:
      boothId:
        description: 摊位id
        type: integer
      description:
        description: 描述
        type: string
      name:
        description: 名称
        type: string
      price:
        description: 价格
        type: number
      status:
        description: 状态
        type: integer
      stock:
        description: 库存
        type: integer
      type:
        description: 类型
        type: integer
      wId:
        description: 商品id
        type: integer
    type: object
  query.WaresEditQuery:
    description: 更新商品模型
    properties:
      name:
        description: 名称
        type: string
      price:
        description: 价格
        type: number
      status:
        description: 状态
        type: integer
      stock:
        description: 库存
        type: integer
      type:
        description: 类型
        type: integer
      wId:
        description: 商品id
        type: integer
    type: object
  query.WaresPageQuery:
    description: 分页获取商品请求模型
    properties:
      boothId:
        description: 摊位id
        type: integer
      pageNo:
        description: 页号
        type: integer
      pageSize:
        description: 页数
        type: integer
      status:
        description: 状态
        type: integer
      type:
        description: 类型
        type: integer
      userId:
        description: 摊主
        type: integer
    type: object
  utils.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 消息
        type: string
    type: object
info:
  contact: {}
paths:
  /booth/add:
    post:
      consumes:
      - application/json
      description: 添加一个摊位的信息
      parameters:
      - description: 摊位信息
        in: body
        name: booth
        required: true
        schema:
          $ref: '#/definitions/query.BoothAddQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 添加摊位
      tags:
      - 摊位模块
  /booth/detail:
    get:
      consumes:
      - application/json
      description: 获取一个摊位的详情
      parameters:
      - description: 摊位id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 摊位详情
      tags:
      - 摊位模块
  /booth/edit:
    post:
      consumes:
      - application/json
      description: 编辑一个摊位的信息
      parameters:
      - description: 摊位信息
        in: body
        name: booth
        required: true
        schema:
          $ref: '#/definitions/query.EditBoothQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 编辑摊位
      tags:
      - 摊位模块
  /booth/page:
    get:
      consumes:
      - application/json
      description: 获取摊位列表
      parameters:
      - description: 页号
        in: query
        name: pageNo
        type: integer
      - description: 页数
        in: query
        name: pageSize
        type: integer
      - description: 状态
        in: query
        name: status
        type: integer
      - description: 类型
        in: query
        name: type
        type: integer
      - description: 摊主
        in: query
        name: userId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 摊位列表
      tags:
      - 摊位模块
  /boothType/add:
    post:
      consumes:
      - application/json
      description: 添加一个摊位类型信息
      parameters:
      - description: 摊位类型信息
        in: body
        name: boothType
        required: true
        schema:
          $ref: '#/definitions/query.BoothTypeAddQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 添加摊位类型
      tags:
      - 摊位类型模块
  /boothType/detail:
    get:
      consumes:
      - application/json
      description: 获取一个摊位类型信息
      parameters:
      - description: 摊位类型id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取摊位详情
      tags:
      - 摊位类型模块
  /boothType/edit:
    post:
      consumes:
      - application/json
      description: 编辑一个摊位类型信息
      parameters:
      - description: 摊位类型信息
        in: body
        name: boothType
        required: true
        schema:
          $ref: '#/definitions/query.BoothTypeEditQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 编辑摊位类型
      tags:
      - 摊位类型模块
  /boothType/page:
    get:
      consumes:
      - application/json
      description: 获取摊位类型列表
      parameters:
      - description: 页号
        in: query
        name: pageNo
        required: true
        type: integer
      - description: 每页的数据量
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取摊位类型列表
      tags:
      - 摊位类型模块
  /file/add:
    post:
      consumes:
      - application/json
      description: 添加一个文件
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 添加文件
      tags:
      - 文件模块
  /file/del:
    post:
      consumes:
      - application/json
      description: 根据文件id删除文件
      parameters:
      - description: 文件id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 删除文件
      tags:
      - 文件模块
  /file/detail:
    get:
      consumes:
      - application/json
      description: 根据文件id获取文件详情
      parameters:
      - description: 文件id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 文件详情
      tags:
      - 文件模块
  /user/getLoginUser:
    get:
      consumes:
      - application/json
      description: 需要邮箱验证，用户修改密码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户修改密码
      tags:
      - 用户模块
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/query.UserLoginQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户登录
      tags:
      - 用户模块
  /user/modifyUsername:
    post:
      consumes:
      - application/json
      description: 用户更改昵称
      parameters:
      - description: 用户昵称
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户更改昵称
      tags:
      - 用户模块
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/query.UserAddQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户注册
      tags:
      - 用户模块
  /user/sendModifyCode:
    get:
      consumes:
      - application/json
      description: 获取更改密码邮箱验证码
      parameters:
      - description: 用户邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取更改密码邮箱验证码
      tags:
      - 用户模块
  /user/sendRegCode:
    get:
      consumes:
      - application/json
      description: 获取注册邮箱验证码
      parameters:
      - description: 用户邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取注册邮箱验证码
      tags:
      - 用户模块
  /user/updateAvatar:
    post:
      consumes:
      - application/json
      description: 用户更新头像图片
      parameters:
      - description: 文件id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 更新用户头像
      tags:
      - 用户模块
  /user/updateInfo:
    post:
      consumes:
      - application/json
      description: 用户信息修改接口
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/query.UserUpdateInfoQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户信息修改
      tags:
      - 用户模块
  /user/updatePwd:
    post:
      consumes:
      - application/json
      description: 用户修改密码
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/query.UserUpdatePwdQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 用户修改密码
      tags:
      - 用户模块
  /utils/decodeRsa:
    get:
      consumes:
      - application/json
      description: 获取RSA私钥解密数据的数据
      parameters:
      - description: 需要解密的数据
        in: query
        name: cipher
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取私钥解密数据
      tags:
      - 通用模块
  /utils/encodeRsa:
    get:
      consumes:
      - application/json
      description: 获取RSA公钥加密的数据
      parameters:
      - description: 需要加密的数据
        in: query
        name: plain
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取公钥的数据
      tags:
      - 通用模块
  /utils/getPublicRsaKey:
    get:
      consumes:
      - application/json
      description: 获取RSA加密公钥
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 获取加密公钥
      tags:
      - 通用模块
  /wares/add:
    post:
      consumes:
      - application/json
      description: 添加一个商品
      parameters:
      - description: 商品信息
        in: body
        name: wares
        required: true
        schema:
          $ref: '#/definitions/query.WaresAddQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 添加商品
      tags:
      - 商品模块
  /wares/detail:
    get:
      consumes:
      - application/json
      description: 获取商品详细信息
      parameters:
      - description: 商品id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 商品详情
      tags:
      - 商品模块
  /wares/edit:
    post:
      consumes:
      - application/json
      description: 编辑一个商品
      parameters:
      - description: 商品信息
        in: body
        name: wares
        required: true
        schema:
          $ref: '#/definitions/query.WaresEditQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 编辑商品
      tags:
      - 商品模块
  /wares/page:
    get:
      consumes:
      - application/json
      description: 分页获取商品信息
      parameters:
      - description: 商品分页信息
        in: body
        name: wares
        required: true
        schema:
          $ref: '#/definitions/query.WaresPageQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Result'
      summary: 商品列表
      tags:
      - 商品模块
swagger: "2.0"
